name: human
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.9.1=hac33072_0
  - atk-1.0=2.38.0=h04ea711_2
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.18.2=h3394656_1
  - dav1d=1.2.1=h5eee18b_0
  - ffmpeg=7.1.0=gpl_h9d2eab1_509
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=12.0.0=hba01fac_0
  - gtk2=2.24.33=h8ee276e_7
  - gts=0.7.6=h977cf35_4
  - harfbuzz=10.2.0=h4bba637_0
  - icu=75.1=he02047a_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.20.2=h84d6215_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libass=0.17.3=hba53ac1_1
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgd=2.3.3=h6f5c62b_11
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libopenvino=2024.6.0=hac27bb2_3
  - libopenvino-auto-batch-plugin=2024.6.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2024.6.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2024.6.0=h3f63f65_3
  - libopenvino-intel-cpu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-intel-gpu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-intel-npu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-ir-frontend=2024.6.0=h3f63f65_3
  - libopenvino-onnx-frontend=2024.6.0=h6363af5_3
  - libopenvino-paddle-frontend=2024.6.0=h6363af5_3
  - libopenvino-pytorch-frontend=2024.6.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2024.6.0=h630ec5c_3
  - libopenvino-tensorflow-lite-frontend=2024.6.0=h5888daf_3
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.45=h943b412_0
  - libprotobuf=5.28.3=h6128344_1
  - librsvg=2.58.4=h49af25d_2
  - libsqlite=3.48.0=hee588c1_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.4=h6a678d5_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openfst=1.8.2=h924138e_2
  - openh264=2.5.0=hf92e6e3_0
  - openssl=3.4.0=h7b32b05_1
  - pango=1.56.0=h861ebed_0
  - pcre2=10.44=hba22ea6_2
  - pip=24.2=py39h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.14=h59595ed_0
  - pynini=2.1.5=py39h7633fee_6
  - python=3.9.18=h0755675_1_cpython
  - python_abi=3.9=5_cp39
  - readline=8.2=h5eee18b_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.13.0=0
  - svt-av1=2.3.0=h5888daf_0
  - tbb=2022.0.0=hceb3a55_0
  - tk=8.6.13=noxft_h4845f30_101
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wheel=0.44.0=py39h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.10.1
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - albucore==0.0.23
      - albumentations==2.0.5
      - alembic==1.16.5
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==24.3.0
      - audioread==3.0.1
      - autopage==0.5.2
      - av==14.0.1
      - babel==2.17.0
      - backcall==0.2.0
      - beartype==0.19.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - build==1.2.2.post1
      - cachetools==5.5.1
      - certifi==2022.12.7
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==3.0.4
      - charset-normalizer==2.0.12
      - chumpy==0.70
      - click==8.1.8
      - cliff==4.9.1
      - cmaes==0.12.0
      - cmd2==2.7.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.2
      - configargparse==1.7
      - conformer==0.3.2
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==44.0.0
      - csvw==3.5.1
      - cycler==0.12.1
      - cython==3.0.11
      - datasets==2.18.0
      - dearpygui==2.0.0
      - debugpy==1.8.12
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.14.2
      - defusedxml==0.7.1
      - diffusers==0.30.2
      - dill==0.3.8
      - distlib==0.4.0
      - distro==1.9.0
      - dlib==19.24.6
      - dlinfo==2.0.0
      - docopt==0.6.2
      - easydict==1.13
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - face-alignment==1.4.1
      - fairscale==0.4.13
      - faiss-cpu==1.8.0
      - fastapi==0.112.0
      - fastapi-cli==0.0.4
      - fastjsonschema==2.21.1
      - ffmpeg-python==0.2.0
      - ffmpy==0.5.0
      - filelock==3.14.0
      - fire==0.7.0
      - flatbuffers==25.1.21
      - fonttools==4.55.4
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gdown==5.1.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - googletrans==4.0.0rc1
      - gradio==3.43.2
      - gradio-client==0.5.0
      - greenlet==3.2.4
      - grpcio==1.57.0
      - grpcio-tools==1.57.0
      - h11==0.14.0
      - h2==3.2.0
      - h5py==3.13.0
      - hf-xet==1.1.9
      - hjson==3.1.0
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - hyperframe==5.2.0
      - hyperpyyaml==1.2.2
      - identify==2.6.14
      - idna==2.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - inflect==7.3.1
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - insightface==0.7.3
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - isodate==0.7.2
      - isoduration==20.11.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.3
      - jiter==0.10.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - json-tricks==3.17.3
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keras==3.9.1
      - kiwisolver==1.4.7
      - kornia==0.5.0
      - langchain-core==0.3.75
      - langchain-huggingface==0.3.1
      - langsmith==0.4.23
      - language-tags==1.2.0
      - lazy-loader==0.4
      - libaio==0.9.3
      - librosa==0.10.2
      - lightning==2.2.4
      - lightning-utilities==0.11.9
      - llvmlite==0.43.0
      - lpips==0.1.4
      - mako==1.3.10
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matcha==0.3
      - matcha-tts==0.0.7.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapipe==0.10.20
      - mistune==3.1.2
      - ml-dtypes==0.5.1
      - mmcv==2.1.0
      - mmdet==3.1.0
      - mmengine==0.10.6
      - mmpose==1.1.0
      - model-index==0.1.11
      - modelscope==1.15.0
      - more-itertools==10.6.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mtcnn==0.1.1
      - multidict==6.1.0
      - multiprocess==0.70.16
      - munch==4.0.0
      - munkres==1.1.4
      - namex==0.0.8
      - narwhals==1.23.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.3
      - nodeenv==1.9.1
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-ml-py==12.570.86
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.16.0
      - onnxruntime-gpu==1.18.0
      - openai==1.107.1
      - openai-whisper==20231117
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - openxlab==0.1.2
      - opt-einsum==3.4.0
      - optree==0.14.1
      - optuna==2.10.1
      - ordered-set==4.1.0
      - orjson==3.10.15
      - oss2==2.17.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pfzy==0.3.4
      - phonemizer==3.3.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pip-tools==7.4.1
      - pipdeptree==2.25.0
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - pluggy==1.6.0
      - pooch==1.8.2
      - portalocker==3.1.1
      - praat-parselmouth==0.4.5
      - pre-commit==4.3.0
      - pretrainedmodels==0.7.4
      - prettytable==3.16.0
      - proglog==0.1.10
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==4.25.0
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyaudio==0.2.14
      - pycocotools==2.0.10
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.11.0
      - pydantic-core==2.33.0
      - pydub==0.25.1
      - pygments==2.19.1
      - pyloudnorm==0.1.1
      - pymcubes==0.1.6
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pyperclip==1.9.0
      - pypinyin==0.42.0
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.9
      - pyqt5-plugins==5.15.9.2.3
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pyqt5-tools==5.15.9.3.3
      - pysocks==1.7.1
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - python-speech-features==0.6
      - pytorch-lightning==2.5.0.post0
      - pytorch3d==0.7.8
      - pytz==2023.4
      - pyworld==0.2.1rc0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - qt5-applications==5.15.2.2.3
      - qt5-tools==5.15.2.1.3
      - rdflib==7.1.4
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986==1.5.0
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rich-argparse==1.7.1
      - rootutils==1.0.7
      - rpds-py==0.22.3
      - rsa==4.9
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - ruff==0.9.2
      - s3prl==0.4.17
      - safetensors==0.5.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.11.1
      - seaborn==0.13.2
      - segments==2.3.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - setuptools==60.2.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - simplejson==3.19.3
      - simsimd==6.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sounddevice==0.5.1
      - soundfile==0.12.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - sqlalchemy==2.0.43
      - stack-data==0.6.3
      - starlette==0.37.2
      - stevedore==5.5.0
      - stringzilla==3.12.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorrt-cu12==10.0.1
      - tensorrt-cu12-bindings==10.0.1
      - tensorrt-cu12-libs==10.0.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - textgrid==1.6.1
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - tiktoken==0.8.0
      - timm==1.0.14
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.1.0+cu121
      - torchaudio==2.1.0+cu121
      - torchdiffeq==0.2.5
      - torchmetrics==1.6.1
      - torchode==1.0.0
      - torchshow==0.4.1
      - torchtyping==0.1.5
      - torchvision==0.16.0+cu121
      - tornado==6.4.2
      - tqdm==4.65.2
      - traitlets==5.14.3
      - transformers==4.41.0
      - trimesh==4.6.0
      - triton==2.1.0
      - ttsfrd-dependency==0.1
      - typeguard==4.4.1
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - unidecode==1.4.0
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - urllib3==1.26.20
      - uvicorn==0.30.0
      - virtualenv==20.34.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - webrtcvad==2.0.10
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.1.3
      - wetextprocessing==1.0.3
      - wget==3.2
      - widgetsnbextension==4.0.14
      - xtcocotools==1.14.3
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarg==0.1.9
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.24.0
prefix: /home/caotiezheng/anaconda3/envs/human
