accumulate_grad_batches: 1
add_ffhq_singe_disc: false
also_update_decoder: false
amp: false
appearance_feat_mul_torso_mask: true
base_channel: 32768
base_config:
- ./secc_img2plane_orig.yaml
batch_size: 1
binary_data_dir: data/binary/CelebV-HQ
blur_fade_kimg: 20
blur_init_sigma: 10
blur_raw_target: true
box_warp: 1
ckpt_milestone_interval: 50000
clip_grad_norm: 1.0
clip_grad_value: 0
cond_hid_dim: 32
cond_out_dim: 16
cond_type: idexp_lm3d_normalized
debug: false
density_reg_p_dist: 0.004
disable_highreso_at_stage1: true
disc_c_noise: 1.0
disc_cond_mode: none
ds_name: FULL_Concat_VFHQ_CelebVHQ_TH1KH_RAVDESS
ema_interval: 400
enable_rescale_plane_regulation: false
eval_max_batches: 100
ffhq_disc_inp_mode: eg3d_gen
final_resolution: 512
flipped_to_world_coord: true
fuse_with_deform_source: false
gen_cond_mode: none
generator_condition_on_pose: true
gpc_reg_fade_kimg: 1000
gpc_reg_prob: 0.8
group_size_for_mini_batch_std: 2
htbsr_head_threshold: 0.9
htbsr_head_weight_fuse_mode: v2
img2plane_backbone_mode: composite
img2plane_backbone_scale: standard
init_from_ckpt: checkpoints/240207_robust_secc2plane/secc2plane_orig_blink0.3_pertubeNone/model_ckpt_steps_150000.ckpt
lam_occlusion_2_reg_l1: 0.0
lam_occlusion_reg_l1: 0.0
lam_occlusion_weights_entropy: 0.001
lambda_G_adversarial_adv: 1.0
lambda_G_supervise_adv: 1.0
lambda_G_supervise_mse: 1.0
lambda_G_supervise_mse_raw: 1.0
lambda_density_reg: 0.25
lambda_ffhq_mv_adv: 0.002
lambda_gradient_penalty: 1.0
lambda_mse: 1.0
lambda_mse_depth: 0.0
lambda_th1kh_mv_adv: 0.003
lambda_weights_entropy: 0.01
lambda_weights_l1: 0.1
load_ckpt: ''
lpips_mode: vgg19_v2
lr_d: 0.0002
lr_decay_interval: 5000
lr_decay_rate: 0.95
lr_g: 1.0e-05
lr_lambda_pertube_secc: 0.01
lr_mul_cano_img2plane: 1.0
mapping_network_depth: 2
max_channel: 512
max_updates: 100000
mimic_plane: false
min_rescale_factor: 0.25
motion_smo_win_size: 5
neural_rendering_resolution: 128
normalize_cond: false
normalize_radius: false
not_save_modules:
- criterion_lpips
- eg3d_model
num_ckpt_keep: 1
num_fp16_layers_in_discriminator: 4
num_fp16_layers_in_generator: 0
num_fp16_layers_in_super_resolution: 4
num_samples_coarse: 48
num_samples_fine: 48
num_sanity_val_steps: 1
num_valid_plots: 25
num_workers: 8
ones_ws_for_sr: true
optimizer_adam_beta1_d: 0.0
optimizer_adam_beta1_g: 0.0
optimizer_adam_beta2_d: 0.99
optimizer_adam_beta2_g: 0.99
phase1_plane_fusion_mode: add
pncc_cond_mode: cano_src_tgt
pretrained_eg3d_ckpt: /home/tiger/projects/GeneFace_private/checkpoints/geneface2_ckpts/eg3d_baseline_run2/model_ckpt_steps_100000.ckpt
print_nan_grads: false
process_id: 0
processed_data_dir: data/processed/videos
random_sample_pose: true
raw_data_dir: /home/tiger/datasets/raw/FFHQ
ray_far: auto
ray_near: auto
reg_interval_d: 16
reg_interval_g: 4
reg_interval_g_cond: 4
reload_head_ckpt: ''
resume_from_checkpoint: 0
save_best: true
save_codes:
- tasks
- modules
- egs
secc_pertube_mode: randn
secc_pertube_randn_scale: 0.01
secc_segformer_scale: b0
seed: 9999
seg_out_mode: head
smo_win_size: 5
split_seed: 999
sr_type: vanilla
start_adv_iters: 40000
target_pertube_blink_secc_loss: 0.15
target_pertube_secc_loss: 0.5
task_cls: tasks.os_avatar.secc_img2plane_torso_task.SECC_Img2PlaneEG3D_TorsoTask
tb_log_interval: 100
torch_compile: true
torso_inp_mode: rgb_alpha
torso_kp_num: 4
torso_model_version: v2
torso_occlusion_reg_unmask_factor: 0.3
torso_ref_segout_mode: torso
total_process: 1
triplane_depth: 1
triplane_feature_type: triplane
triplane_hid_dim: 32
two_stage_training: true
update_on_th1kh_samples: false
update_src2src_interval: 16
use_kv_dataset: true
use_motion_smo_net: false
use_mse: false
use_th1kh_disc: false
use_th1kh_mv_adv: false
val_check_interval: 2000
valid_infer_interval: 2000
valid_monitor_key: val_loss
valid_monitor_mode: min
video_id: May
w_dim: 512
warmup_updates: 4000
weight_fuse: true
work_dir: checkpoints/240210_real3dportrait_orig/secc2plane_torso_orig
z_dim: 512
